### ISSUE TITLE
Öresundståg har ändrat layout på sms

### ISSUE THREAD

**Issue by MWallin** [johkin/Ticket2Calendar#8]
Hej,

Öresundståg har ändrat layouten/formatet på de sms-biljetter de skickar ut. 

Här kommer en bild på hur det såg ut tidigare. 
![2013-03-24 18 40 05](https://f.cloud.github.com/assets/3184624/295701/bd852740-94aa-11e2-8b2e-276d19de399b.png)

Så här ser det ut nu.
![2013-03-24 18 39 58](https://f.cloud.github.com/assets/3184624/295702/c79b53e4-94aa-11e2-9782-58f3339411a8.png)

Säg till om det behövs ytterliggare uppgifter eller om jag kan bistå med något annat.

För övrigt så är detta en kanonapp och funktionen för Öresundståg är toppen och har fungerat jättebra tills för någon vecka sen när de gjorde en förändring.

**Comment by siradamsapple** [comment]
Ser den fortfarande ut så? Mvh Adam

**Comment by johkin** [comment]
Jag har inte gjort någon utveckling av appen sedan den togs bort från Play Store 2014, så jag hoppas att det finns bättre alternativ numera!
